### PR TITLE
Fix Mixin errors

### PR DESCRIPTION
**Pull request by dnastajus**
Hi! This PR fixes Mixin errors that could have been observed in the log on startup if soft dependencies are missing, additionally I have noticed the mod has been injecting Cyclic's code into base MineColonies, when it is a soft dependency, which is also fixed. The best practice with Mixins, when you mixin into the code of a soft dependency is to have `IMixinConfigPlugin`, so that you can prevent Mixin from applying based on certain conditions. Feel free to object.

### CODE REVIEW

**Comment by gisellevonbingen** [comment]
What... Did i used Cyclic's FluidAttribute class? So shame of me.
Thanks for great point. Fixed at 72dc5e4334c8b082d417e3932ba5400323101eac

**Comment by gisellevonbingen** [comment]
'Fix recipe erroring when Simple Storage Network is not present' is applied at ec0e09b3231583d60358f3a267039c44bf441bc1

**Comment by lluminanoctis** [comment]
> What... Did i used Cyclic's FluidAttribute class? So shame of me. Thanks for great point. Fixed at [72dc5e4](https://github.com/gisellevonbingen-Minecraft/MineColonies_Compatibility/commit/72dc5e4334c8b082d417e3932ba5400323101eac)

I presume it was the automatic import from an IDE at fault:)

**Comment by gisellevonbingen** [comment]
I used translation for my poor English.

If there is no mixin target, an error message will be printed, but the game will not be affected.
And I know that many mods use this without plugins.

It seems a bit cumbersome to modify two files (json and plugin) when adding a mixin target.
Is there a way to add a mixin only in the plugin without modifying the json file?

**Comment by lluminanoctis** [comment]
> I used translation for my poor English.
> 
> If there is no mixin target, an error message will be printed, but the game will not be affected. And I know that many mods use this without plugins.
> 
> It seems a bit cumbersome to modify two files (json and plugin) when adding a mixin target. Is there a way to add a mixin only in the plugin without modifying the json file?

Most likely no, there is no method for this in the interface, from the javadoc description MixinConfigPlugin exists as a companion to Mixin configuration (the .json), to veto mixins from loading and the mixins themselves should be declared in the config. Also I am aware that many mods ignore it and don't use MixinConfigPlugin, as I said it is just best practice to keep everything clean.

**Pull request closed without merging**
